version: '3'

services:
  app:
    image: node:12
    container_name: node-js
    environment:
      - TZ=Asia/Tokyo
      - DEBUG=app:*
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./myapp:/app
    working_dir: /app
    command: npm start
  db:
    environment:
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: root
      MYSQL_DATABASE: mysql-db
      TZ: 'Asia/Tokyo'
    image: mysql:5.7
    container_name: db_mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
