version: '3'

services:
  db_mysql:
    env_file: ./docker/db/mysql.env
    environment:
      TZ: 'Asia/Tokyo'
    image: mysql:5.7
    container_name: db_mysql
    hostname: db_mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    networks:
      - my-network
  app:
    image: node:12
    container_name: node-js
    env_file: ./myapp/app.env
    environment:
      - TZ=Asia/Tokyo
      - DEBUG=app:*
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./myapp:/app
    working_dir: /app
    command: npm start
    depends_on: 
      - 'db_mysql'
    networks:
      - my-network
networks:
  my-network:
    external: true
